// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// inv
NumericMatrix inv(const arma::mat& X);
RcppExport SEXP debugpkg_inv(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    __result = Rcpp::wrap(inv(X));
    return __result;
END_RCPP
}
// inv_sympd
NumericMatrix inv_sympd(const arma::mat& X);
RcppExport SEXP debugpkg_inv_sympd(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    __result = Rcpp::wrap(inv_sympd(X));
    return __result;
END_RCPP
}
