# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inv <- function(X) {
    .Call('debugpkg_inv', PACKAGE = 'debugpkg', X)
}

inv_sympd <- function(X) {
    .Call('debugpkg_inv_sympd', PACKAGE = 'debugpkg', X)
}

